version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./sqlinjection_demo:/var/www/html

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sql_demo
    volumes:
      - ./sqlinjection_demo/database.sql:/docker-entrypoint-initdb.d/database.sql